### ISSUE TITLE
is this library useable?

### ISSUE THREAD

**Issue by orangeagain** [kitbashery/xatlas-for-Unity#2]
I can't find any dll,what shoud i do?

**Comment by ghost** [comment]
It needs to be turned into a managed dll, it's an open issue #1 . I've been
putting it off since I've never done it in C++ the wrapper should work fine
once the unmanaged dlls are compiled into a managed dll.

**Comment by orangeagain** [comment]
there is some error in main.cpp

`51//decl.rotateCharts = allowRotate;
52//decl.singleChart = true;
69//xatlas::ParameterizeCharts((xatlas::Atlas*)atlas);
`
after noted this lines. I compile to this dll.
after run it in unity. Do not apear any error.
is this a right way?
[xatlasLib.zip](https://github.com/kitbashery/xatlas-for-Unity/files/5288795/xatlasLib.zip)

**Comment by kitbashery** [comment]
I'm away from my workstation atm.

Is the error coming from the wrapper or the dll you compiled? If it's the
wrapped I can try and fix it later today.

Could you put in a pull request for the dll you made so I can take a look.

You could also contact the original author of the forked repo who wrote the
c++ if the dll is what is throwing the error.

**Comment by ghost** [comment]
Did you compile the xatlasAPIWrapper.cs in with the DLL? 

That file can be left out, just main.cpp, xatlas.cpp and xatlas.h need to be compiled into a managed DLL.

**Comment by ghost** [comment]
It seems the DLL you compiled worked. I'll have to test the C# wrapper. I created a new branch that contains the C++ source and made sure the master branch only included the managed DLL and not the source unmanaged C++ code.
